import javax.swing.JFrame;
import javax.swing.ImageIcon;


public class Juegos extends javax.swing.JFrame {
    
    private Escalar escalar = new Escalar();
    private Bars barras;

    public Juegos() {
        initComponents();
        setLocationRelativeTo(null);
        escalar.escalarLabel(TableroJu, "/imagenes/TableroJ.jpeg");
        escalar.escalarButton(Back1, "/imagenes/Back.jpeg");
        escalar.escalarButton(Laberinto, "/imagenes/Laberinto.jpeg");
        escalar.escalarButton(Snake, "/imagenes/Sanke.jpeg");
        escalar.escalarButton(proximamente, "/imagenes/proximamente.jpg");
        escalar.escalarButton(proximamente2, "/imagenes/proximamente.jpg");
        
     barras = new Bars(IconoCa, IconoAg, IconoPi);   

    }
    
    public Bars getBars() {
        return barras;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconoPi = new javax.swing.JProgressBar();
        IconoCa = new javax.swing.JProgressBar();
        IconoAg = new javax.swing.JProgressBar();
        Laberinto = new javax.swing.JButton();
        TableroJ = new javax.swing.JLabel();
        Snake = new javax.swing.JButton();
        proximamente = new javax.swing.JButton();
        proximamente2 = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        TableroJu = new javax.swing.JLabel();

        IconoPi.setValue(100);

        IconoAg.setValue(100);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Laberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaberintoActionPerformed(evt);
            }
        });
        getContentPane().add(Laberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, 100));
        getContentPane().add(TableroJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Snake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnakeActionPerformed(evt);
            }
        });
        getContentPane().add(Snake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 100));

        proximamente.setText("jButton1");
        proximamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximamenteActionPerformed(evt);
            }
        });
        getContentPane().add(proximamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 100));

        proximamente2.setText("jButton1");
        getContentPane().add(proximamente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 100));

        Back1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Back1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        getContentPane().add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 40));
        getContentPane().add(TableroJu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proximamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximamenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proximamenteActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        Juego v6 = new Juego();
        v6.setVisible(true);
        this.setVisible(false);
        
        v6.getBars().setProgresoBar1Value(barras.getProgresoBar1Value());
        v6.getBars().setProgresoBar2Value(barras.getProgresoBar2Value());
        v6.getBars().setProgresoBar3Value(barras.getProgresoBar3Value());
    }//GEN-LAST:event_Back1ActionPerformed

    private void LaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaberintoActionPerformed
        JFrame laberintoFrame = new JFrame("Laberinto");
        JLaberinto laberintoPanel = new JLaberinto(laberintoFrame);

        laberintoFrame.add(laberintoPanel);
        laberintoFrame.setSize(920, 540);
        laberintoFrame.setLocationRelativeTo(null);
        laberintoFrame.setVisible(true);
        

        this.setVisible(false);
    }//GEN-LAST:event_LaberintoActionPerformed

    private void SnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnakeActionPerformed
        MainFrame mainFrame = new MainFrame(this);
        mainFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SnakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JProgressBar IconoAg;
    private javax.swing.JProgressBar IconoCa;
    private javax.swing.JProgressBar IconoPi;
    private javax.swing.JButton Laberinto;
    private javax.swing.JButton Snake;
    private javax.swing.JLabel TableroJ;
    private javax.swing.JLabel TableroJu;
    private javax.swing.JButton proximamente;
    private javax.swing.JButton proximamente2;
    // End of variables declaration//GEN-END:variables
}
