public class Juego extends javax.swing.JFrame {
    
    private Bars barras;
    private Escalar escalar = new Escalar();

    public Juego() {
        initComponents();
        setLocationRelativeTo(null);
        jLabelNombre.setText("Nombre: " + DatosMascota.getNombreMascota());
        escalar.escalarLabel(jLabelImagenMascota, DatosMascota.getRutaImagen());
        escalar.escalarButton(IconoC, "/imagenes/IconoC.jpeg");
        escalar.escalarButton(Next3, "/imagenes/NextV.jpeg");
        escalar.escalarButton(Next4, "/imagenes/NextV.jpeg");

        // Inicializa Bars con las JProgressBar del formulario
        barras = new Bars(IconoCa, IconoAg, IconoPi);
    }
    
    public Bars getBars() {
        return barras;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next1 = new javax.swing.JButton();
        Next3 = new javax.swing.JButton();
        Next4 = new javax.swing.JButton();
        IconoC = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        IconoCa = new javax.swing.JProgressBar();
        IconoAg = new javax.swing.JProgressBar();
        IconoPi = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelImagenMascota = new javax.swing.JLabel();

        Next1.setText("juego");
        Next1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Next3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next3ActionPerformed(evt);
            }
        });
        getContentPane().add(Next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 40));

        Next4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Next4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next4ActionPerformed(evt);
            }
        });
        getContentPane().add(Next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 40));

        IconoC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        IconoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IconoCActionPerformed(evt);
            }
        });
        getContentPane().add(IconoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 60));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabelNombre.setText("jLabelNombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));
        getContentPane().add(IconoCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        IconoAg.setValue(100);
        getContentPane().add(IconoAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));

        IconoPi.setValue(100);
        getContentPane().add(IconoPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("HAMBRE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("SUEÑO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("SED:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        jLabelImagenMascota.setToolTipText("");
        getContentPane().add(jLabelImagenMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Next4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next4ActionPerformed
        Comer v5 = new Comer();
        v5.setVisible(true);
        this.setVisible(false);
        
        v5.getBars().setProgresoBar1Value(barras.getProgresoBar1Value());
        v5.getBars().setProgresoBar2Value(barras.getProgresoBar2Value());
        v5.getBars().setProgresoBar3Value(barras.getProgresoBar3Value());

    }//GEN-LAST:event_Next4ActionPerformed

    private void Next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next3ActionPerformed
        Dormir v4 = new Dormir();
        v4.setVisible(true);
        this.setVisible(false);
        
        v4.getBars().setProgresoBar1Value(barras.getProgresoBar1Value());
        v4.getBars().setProgresoBar2Value(barras.getProgresoBar2Value());
        v4.getBars().setProgresoBar3Value(barras.getProgresoBar3Value());
    }//GEN-LAST:event_Next3ActionPerformed

    private void IconoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IconoCActionPerformed
        Juegos v8 = new Juegos();
        v8.setVisible(true);
        this.setVisible(false);
        
        v8.getBars().setProgresoBar1Value(barras.getProgresoBar1Value());
        v8.getBars().setProgresoBar2Value(barras.getProgresoBar2Value());
        v8.getBars().setProgresoBar3Value(barras.getProgresoBar3Value());
    }//GEN-LAST:event_IconoCActionPerformed

    private void Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next1ActionPerformed


    }//GEN-LAST:event_Next1ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dormir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dormir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dormir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dormir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar IconoAg;
    private javax.swing.JButton IconoC;
    private javax.swing.JProgressBar IconoCa;
    private javax.swing.JProgressBar IconoPi;
    private javax.swing.JButton Next1;
    private javax.swing.JButton Next3;
    private javax.swing.JButton Next4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImagenMascota;
    private javax.swing.JLabel jLabelNombre;
    // End of variables declaration//GEN-END:variables
}
