public class Ventana3 extends javax.swing.JFrame {

    private String NombreMascota;
    Escalar escalar = new Escalar();
    
    
    public Ventana3() {
        initComponents();
        setLocationRelativeTo(null);
        escalar.escalarLabel(TableroM, "/imagenes/TableroN.jpeg");
        escalar.escalarButton(GuardarNombre, "/imagenes/Guardar.jpeg");
        escalar.escalarButton(Abrir4, "/imagenes/NextA.jpeg");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Abrir4 = new javax.swing.JButton();
        AsignarNombre = new javax.swing.JTextField();
        GuardarNombre = new javax.swing.JButton();
        TableroM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Abrir4.setEnabled(false);
        Abrir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abrir4ActionPerformed(evt);
            }
        });
        getContentPane().add(Abrir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 330, 140, 40));

        AsignarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AsignarNombreKeyReleased(evt);
            }
        });
        getContentPane().add(AsignarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, 40));

        GuardarNombre.setEnabled(false);
        GuardarNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 40));

        TableroM.setToolTipText("");
        getContentPane().add(TableroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Abrir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abrir4ActionPerformed
        Dormir v4 = new Dormir();
        v4.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_Abrir4ActionPerformed

    private void AsignarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AsignarNombreKeyReleased
     
        if (!AsignarNombre.getText().isEmpty()) {
            GuardarNombre.setEnabled(true);
        } else {
            GuardarNombre.setEnabled(false);
        }

    }//GEN-LAST:event_AsignarNombreKeyReleased

    private void GuardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNombreActionPerformed
        DatosMascota.setNombreMascota(AsignarNombre.getText());
        GuardarNombre.setEnabled(false);
        Abrir4.setEnabled(true);
    }//GEN-LAST:event_GuardarNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir4;
    private javax.swing.JTextField AsignarNombre;
    private javax.swing.JButton GuardarNombre;
    private javax.swing.JLabel TableroM;
    // End of variables declaration//GEN-END:variables


}
