public class Ventana2 extends javax.swing.JFrame {
    
    Escalar escalar = new Escalar();

    public Ventana2() {
        initComponents();
        setLocationRelativeTo(null);
        escalar.escalarLabel(TableroM, "/imagenes/TableroM.jpeg");
        escalar.escalarButton(Mascota1, "/imagenes/Hdino.jpeg");
        escalar.escalarButton(Mascota2, "/imagenes/Hpanda.jpeg");
        escalar.escalarButton(Mascota3, "/imagenes/Hpingu.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mascota1 = new javax.swing.JButton();
        Mascota2 = new javax.swing.JButton();
        Mascota3 = new javax.swing.JButton();
        TableroM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mascota1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Mascota1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mascota1ActionPerformed(evt);
            }
        });
        getContentPane().add(Mascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 145, 101, 102));

        Mascota2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Mascota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mascota2ActionPerformed(evt);
            }
        });
        getContentPane().add(Mascota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 145, 110, 102));

        Mascota3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Mascota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mascota3ActionPerformed(evt);
            }
        });
        getContentPane().add(Mascota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 145, 97, 98));

        TableroM.setToolTipText("");
        getContentPane().add(TableroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mascota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mascota1ActionPerformed
        DatosMascota.setRutaImagen("/imagenes/Dino.jpeg");
        Ventana3 v3 = new Ventana3();
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Mascota1ActionPerformed

    private void Mascota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mascota2ActionPerformed
        DatosMascota.setRutaImagen("/imagenes/Panda.jpeg");
        Ventana3 v3 = new Ventana3();
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Mascota2ActionPerformed

    private void Mascota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mascota3ActionPerformed
        DatosMascota.setRutaImagen("/imagenes/Pinguino.jpeg");
        Ventana3 v3 = new Ventana3();
        v3.setVisible(true);
        this.setVisible(false);        this.setVisible(false);    }//GEN-LAST:event_Mascota3ActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mascota1;
    private javax.swing.JButton Mascota2;
    private javax.swing.JButton Mascota3;
    private javax.swing.JLabel TableroM;
    // End of variables declaration//GEN-END:variables
}
